input_directory: '../data/input'
output_directory: '../data/output'

graph_name: nd-134204506-processletevent

num_samples: 5
epsilon_1_values: [0.01, 0.1, 0.5, 1.0]
epsilon_2_values: [1.0]
alpha_values: [0.5, 1, 2]